CREATE TABLE IF NOT EXISTS stage_derivados_petroleo(
	COMBUSTÍVEL VARCHAR(30),
	ANO INT, 
	REGIÃO VARCHAR(50),
	ESTADO VARCHAR(50),
	UNIDADE VARCHAR(3),
	Jan FLOAT,
	Fev FLOAT,
    Mar FLOAT,
	Abr FLOAT,
	Mai FLOAT,
	Jun FLOAT,
	Jul FLOAT,
	Ago FLOAT,
	"Set" FLOAT,
	"Out" FLOAT,
	Nov FLOAT,
	Dez FLOAT,
	TOTAL FLOAT
)


